### ISSUE TITLE
What does Cards in appView.js do?

### ISSUE THREAD

**Issue by bradley-curran** [bradley-curran/dev-board#10]
I see a bunch of Cards.x functions being called but I can't see where it's declared. 

What am I missing?

**Comment by ksiwei** [comment]
you are missing me :heart:

**Comment by ksiwei** [comment]
ah those are methods coming from backbone collection prototype. For example: http://backbonejs.org/#Collection-create

The advantage of using them is that they will trigger events on models automatically.

**Comment by bradley-curran** [comment]
Ohh, they're defined in cards.js. Makes sense.
